"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-10 01:14:13.140536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('parent_action_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenance_action_type'), 'provenance', ['action_type'], unique=False)
    op.create_index(op.f('ix_provenance_timestamp'), 'provenance', ['timestamp'], unique=False)
    op.create_table('reference_foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_lower', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('serving_size', sa.String(length=50), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('diet_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('allergens', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_foods_barcode'), 'reference_foods', ['barcode'], unique=False)
    op.create_index(op.f('ix_reference_foods_name'), 'reference_foods', ['name'], unique=False)
    op.create_index(op.f('ix_reference_foods_name_lower'), 'reference_foods', ['name_lower'], unique=False)
    op.create_table('reference_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_lower', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('drug_class', sa.String(length=255), nullable=True),
    sa.Column('common_uses', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_medications_name'), 'reference_medications', ['name'], unique=True)
    op.create_index(op.f('ix_reference_medications_name_lower'), 'reference_medications', ['name_lower'], unique=False)
    op.create_table('reference_positive_effects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_lower', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_positive_effects_name'), 'reference_positive_effects', ['name'], unique=True)
    op.create_index(op.f('ix_reference_positive_effects_name_lower'), 'reference_positive_effects', ['name_lower'], unique=False)
    op.create_table('reference_symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_lower', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_symptoms_name'), 'reference_symptoms', ['name'], unique=True)
    op.create_index(op.f('ix_reference_symptoms_name_lower'), 'reference_symptoms', ['name_lower'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('allergies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('medical_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('insight_type', sa.Enum('SUMMARY', 'RECOMMENDATION', 'CORRELATION', 'WARNING', name='insighttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('based_on', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reference_food_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_lower', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('meal_category', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'BEVERAGE', 'SUPPLEMENT', name='mealcategory'), nullable=False),
    sa.Column('serving_size', sa.String(length=50), nullable=True),
    sa.Column('servings', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('diet_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('allergens', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('had_reaction', sa.Boolean(), nullable=True),
    sa.Column('reaction_severity', sa.Integer(), nullable=True),
    sa.Column('reaction_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reference_food_id'], ['reference_foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_logs_meal_category', 'food_logs', ['meal_category'], unique=False)
    op.create_index(op.f('ix_food_logs_name'), 'food_logs', ['name'], unique=False)
    op.create_index(op.f('ix_food_logs_name_lower'), 'food_logs', ['name_lower'], unique=False)
    op.create_index(op.f('ix_food_logs_timestamp'), 'food_logs', ['timestamp'], unique=False)
    op.create_index('ix_food_logs_user_timestamp', 'food_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('health_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_reports_share_token'), 'health_reports', ['share_token'], unique=True)
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reference_medication_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_lower', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('times', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('prescribed_for', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reference_medication_id'], ['reference_medications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_name'), 'medications', ['name'], unique=False)
    op.create_index(op.f('ix_medications_name_lower'), 'medications', ['name_lower'], unique=False)
    op.create_table('positive_effects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('effect_name', sa.String(length=255), nullable=False),
    sa.Column('effect_name_lower', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positive_effects_effect_name'), 'positive_effects', ['effect_name'], unique=False)
    op.create_index(op.f('ix_positive_effects_effect_name_lower'), 'positive_effects', ['effect_name_lower'], unique=False)
    op.create_index(op.f('ix_positive_effects_timestamp'), 'positive_effects', ['timestamp'], unique=False)
    op.create_table('side_effects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_medication_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('medication_name_lower', sa.String(length=255), nullable=False),
    sa.Column('effect_name', sa.String(length=255), nullable=False),
    sa.Column('effect_name_lower', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'VERY_RARE', name='frequencycategory'), nullable=False),
    sa.Column('frequency_percentage', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['reference_medication_id'], ['reference_medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_side_effects_effect_name'), 'side_effects', ['effect_name'], unique=False)
    op.create_index(op.f('ix_side_effects_effect_name_lower'), 'side_effects', ['effect_name_lower'], unique=False)
    op.create_index('ix_side_effects_med_lower_effect_lower', 'side_effects', ['medication_name_lower', 'effect_name_lower'], unique=False)
    op.create_index(op.f('ix_side_effects_medication_name'), 'side_effects', ['medication_name'], unique=False)
    op.create_index(op.f('ix_side_effects_medication_name_lower'), 'side_effects', ['medication_name_lower'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symptom_name', sa.String(length=255), nullable=False),
    sa.Column('symptom_name_lower', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('matches_known_side_effect', sa.Boolean(), nullable=True),
    sa.Column('matched_side_effect_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_logs_symptom_name'), 'symptom_logs', ['symptom_name'], unique=False)
    op.create_index(op.f('ix_symptom_logs_symptom_name_lower'), 'symptom_logs', ['symptom_name_lower'], unique=False)
    op.create_index(op.f('ix_symptom_logs_timestamp'), 'symptom_logs', ['timestamp'], unique=False)
    op.create_table('food_medication_association',
    sa.Column('food_log_id', sa.UUID(), nullable=True),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['food_log_id'], ['food_logs.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], )
    )
    op.create_table('food_symptom_association',
    sa.Column('food_log_id', sa.UUID(), nullable=True),
    sa.Column('symptom_log_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['food_log_id'], ['food_logs.id'], ),
    sa.ForeignKeyConstraint(['symptom_log_id'], ['symptom_logs.id'], )
    )
    op.create_table('positive_effect_medication_association',
    sa.Column('positive_effect_id', sa.UUID(), nullable=True),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['positive_effect_id'], ['positive_effects.id'], )
    )
    op.create_table('symptom_medication_association',
    sa.Column('symptom_log_id', sa.UUID(), nullable=True),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['symptom_log_id'], ['symptom_logs.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom_medication_association')
    op.drop_table('positive_effect_medication_association')
    op.drop_table('food_symptom_association')
    op.drop_table('food_medication_association')
    op.drop_index(op.f('ix_symptom_logs_timestamp'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_symptom_name_lower'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_symptom_name'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index(op.f('ix_side_effects_medication_name_lower'), table_name='side_effects')
    op.drop_index(op.f('ix_side_effects_medication_name'), table_name='side_effects')
    op.drop_index('ix_side_effects_med_lower_effect_lower', table_name='side_effects')
    op.drop_index(op.f('ix_side_effects_effect_name_lower'), table_name='side_effects')
    op.drop_index(op.f('ix_side_effects_effect_name'), table_name='side_effects')
    op.drop_table('side_effects')
    op.drop_index(op.f('ix_positive_effects_timestamp'), table_name='positive_effects')
    op.drop_index(op.f('ix_positive_effects_effect_name_lower'), table_name='positive_effects')
    op.drop_index(op.f('ix_positive_effects_effect_name'), table_name='positive_effects')
    op.drop_table('positive_effects')
    op.drop_index(op.f('ix_medications_name_lower'), table_name='medications')
    op.drop_index(op.f('ix_medications_name'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_health_reports_share_token'), table_name='health_reports')
    op.drop_table('health_reports')
    op.drop_index('ix_food_logs_user_timestamp', table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_timestamp'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_name_lower'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_name'), table_name='food_logs')
    op.drop_index('ix_food_logs_meal_category', table_name='food_logs')
    op.drop_table('food_logs')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reference_symptoms_name_lower'), table_name='reference_symptoms')
    op.drop_index(op.f('ix_reference_symptoms_name'), table_name='reference_symptoms')
    op.drop_table('reference_symptoms')
    op.drop_index(op.f('ix_reference_positive_effects_name_lower'), table_name='reference_positive_effects')
    op.drop_index(op.f('ix_reference_positive_effects_name'), table_name='reference_positive_effects')
    op.drop_table('reference_positive_effects')
    op.drop_index(op.f('ix_reference_medications_name_lower'), table_name='reference_medications')
    op.drop_index(op.f('ix_reference_medications_name'), table_name='reference_medications')
    op.drop_table('reference_medications')
    op.drop_index(op.f('ix_reference_foods_name_lower'), table_name='reference_foods')
    op.drop_index(op.f('ix_reference_foods_name'), table_name='reference_foods')
    op.drop_index(op.f('ix_reference_foods_barcode'), table_name='reference_foods')
    op.drop_table('reference_foods')
    op.drop_index(op.f('ix_provenance_timestamp'), table_name='provenance')
    op.drop_index(op.f('ix_provenance_action_type'), table_name='provenance')
    op.drop_table('provenance')
    # ### end Alembic commands ###
